beg= True
hunt= True
fish= True
pm= True
hl= True
dep= True
dig = True
scout = True
crime = False
gamble = False
BUY_horseshoe = False
USE_horseshoe = False
USE_pizza = False
numberofhorseshoe = 0
numberofpizza = 0
betamount = 1500
