beg= True
hunt= True
fish= True
pm= True
hl= True
dep= True
dig = True
scout = False
crime = False
gamble = False
BUY_horseshoe = False
USE_horseshoe = False
numberofhorseshoe = 0
betamount = 1500
send_id =270904126974590976  #dank memer's id
